ADAPTIVE_ENABLED = True

GROWTH_ENABLED = True
IMPORTANT_MEMORY_ENABLED = True
EMOTION_ENABLED = True
REFLECTION_ENABLED = True
PERSONALITY_GROWTH_ENABLED = True
PREFERENCE_HISTORY_ENABLED = True

MEMORY_SAVE_THRESHOLD = 0.70

REFLECTION_INTERVAL = 5
PREFERENCE_SNAPSHOT_INTERVAL = 10
EMOTION_DECAY_INTERVAL = 3

MAX_RECENT_MESSAGES = 20

DEVELOPER_SESSION_IDS = {
    "__developer_chat__",
}

IGNORED_SESSION_PREFIXES = (
    "__system_",
    "__internal_",
)
