from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

FASTAPI_HOST = "127.0.0.1"
FASTAPI_PORT = 8000

STYLEBERT_HOST = "127.0.0.1"
STYLEBERT_PORT = 5000

VOICEVOX_HOST = "127.0.0.1"
VOICEVOX_PORT = 50021

OLLAMA_HOST = "127.0.0.1"
OLLAMA_PORT = 11434

TOOLS_DIR = BASE_DIR / "tools"
STYLEBERT_DIR = TOOLS_DIR / "Style-Bert-VITS2"
STYLEBERT_SERVER_BAT = STYLEBERT_DIR / "Server.bat"

VOICEVOX_DIR = BASE_DIR / "VOICEVOX"
VOICEVOX_EXE = VOICEVOX_DIR / "VOICEVOX.exe"
